#plotting and creating the .png
if(!file.exists('graphs')) dir.create('graphs')
png(filename = '...graphs/plot4.png', width = 480, height = 480, units='px')
Sys.setlocale(category = "LC_ALL", locale = "english")
par(mfrow = c(2, 2))
plot(data1$DateTime, data1$Global_active_power, xlab = '', ylab = 'Global Active Power (kilowatt)', type = 'l')
plot(data1$DateTime, data1$Voltage, xlab = 'datetime', ylab = 'Voltage', type = 'l')
plot(data1$DateTime, data1$Sub_metering_1, xlab = '', ylab = 'Energy sub metering', type = 'l')
lines(data1$DateTime, data1$Sub_metering_2, col = 'red')
lines(data1$DateTime, data1$Sub_metering_3, col = 'blue')
legend('topright', col = c('black', 'red', 'blue'), legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lwd = 1)
plot(data1$DateTime, data1$Global_reactive_power, xlab = 'datetime', ylab = 'Global_reactive_power', type = 'l')
dev.off()